"""empty message

Revision ID: 713b6060fa03
Revises: 1b3cc140f3ed
Create Date: 2021-03-23 11:49:47.042774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713b6060fa03'
down_revision = '1b3cc140f3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chefs', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chefs', 'bio')
    # ### end Alembic commands ###
